services:
  postgres:
    image: postgres:13-alpine
    container_name: railway-postgres

    restart: "no"

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: railway_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
