spring:
  application:
    name: ticket-booking

  datasource:
    url: jdbc:postgresql://localhost:5432/railway_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: 8dc33af4c987cefe7258d5d5a0f3a91b4ab6a37c94bdb3f26a0dbe8d34d72a89

  expiration: 86400000

pricing:
  multipliers:
    WINDOW: 1.40
    AISLE: 1.20
    MIDDLE: 1.00

logging:
  level:
    org:
      hibernate:
        SQL: ERROR
        orm:
          jdbc:
            bind: ERROR

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  success-url: http://localhost:8080/booking/success?bookingId={CHECKOUT_SESSION_ID}
  cancel-url: http://localhost:8080/booking/cancel
